import type {
  UserProfile,
  PlatformConnection,
  Achievement,
  AggregatedStats,
  ReputationData,
  ActivityEvent,
} from './types'

export const mockUser: UserProfile = {
  id: 'user_1',
  name: 'Alex Chen',
  email: 'alex@example.com',
  role: 'Senior Software Engineer',
  avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=alex',
  bio: 'Full-stack developer passionate about open source and building developer tools.',
  location: 'San Francisco, CA',
  joinedAt: '2024-01-15',
}

export const mockConnections: PlatformConnection[] = [
  {
    id: 'conn_github',
    platform: 'github',
    status: 'verified',
    username: 'alexchen',
    profileUrl: 'https://github.com/alexchen',
    avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=github',
    followerCount: 2847,
    verifiedDataPoints: [
      '156 public repositories',
      '2,847 followers',
      '1,234 contributions this year',
      'Member since 2018',
    ],
    lastVerified: '2026-04-01T10:30:00Z',
    connectedAt: '2026-03-15T08:00:00Z',
  },
  {
    id: 'conn_linkedin',
    platform: 'linkedin',
    status: 'connected',
    username: 'alex-chen-dev',
    profileUrl: 'https://linkedin.com/in/alex-chen-dev',
    avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=linkedin',
    followerCount: 5420,
    verifiedDataPoints: [
      '8 years experience',
      '5,420 connections',
      '12 skills endorsed',
    ],
    connectedAt: '2026-03-20T14:00:00Z',
  },
  {
    id: 'conn_twitter',
    platform: 'twitter',
    status: 'not_connected',
  },
]

export const mockAchievements: Achievement[] = [
  {
    id: 'ach_1',
    title: 'Open Source Pioneer',
    description: 'Created 10+ repositories with over 100 stars combined',
    icon: 'star',
    status: 'claimed',
    progress: 10,
    maxProgress: 10,
    requirement: 'Create 10 repositories with 100+ combined stars',
    source: 'github',
    unlockedAt: '2026-03-20T12:00:00Z',
    claimedAt: '2026-03-21T09:00:00Z',
  },
  {
    id: 'ach_2',
    title: 'Consistent Builder',
    description: 'Maintained a contribution streak of 30+ days',
    icon: 'flame',
    status: 'claimed',
    progress: 45,
    maxProgress: 30,
    requirement: 'Contribute code for 30 consecutive days',
    source: 'github',
    unlockedAt: '2026-02-28T12:00:00Z',
    claimedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'ach_3',
    title: 'Community Leader',
    description: 'Reached 1,000+ followers across platforms',
    icon: 'users',
    status: 'available',
    progress: 8267,
    maxProgress: 10000,
    requirement: 'Accumulate 10,000 followers across all connected platforms',
    source: 'multi',
  },
  {
    id: 'ach_4',
    title: 'Verified Professional',
    description: 'Complete verification on all major platforms',
    icon: 'badge-check',
    status: 'available',
    progress: 1,
    maxProgress: 3,
    requirement: 'Verify your identity on GitHub, LinkedIn, and X',
    source: 'multi',
  },
  {
    id: 'ach_5',
    title: 'Industry Veteran',
    description: 'Demonstrated 5+ years of professional experience',
    icon: 'briefcase',
    status: 'claimed',
    progress: 8,
    maxProgress: 5,
    requirement: 'Have 5+ years of verified work experience',
    source: 'linkedin',
    unlockedAt: '2026-03-22T12:00:00Z',
    claimedAt: '2026-03-22T12:30:00Z',
  },
  {
    id: 'ach_6',
    title: 'Network Builder',
    description: 'Built a professional network of 500+ connections',
    icon: 'network',
    status: 'claimed',
    progress: 5420,
    maxProgress: 500,
    requirement: 'Connect with 500+ professionals on LinkedIn',
    source: 'linkedin',
    unlockedAt: '2026-03-18T12:00:00Z',
    claimedAt: '2026-03-18T14:00:00Z',
  },
  {
    id: 'ach_7',
    title: 'Code Reviewer',
    description: 'Reviewed 50+ pull requests in open source projects',
    icon: 'git-pull-request',
    status: 'available',
    progress: 34,
    maxProgress: 50,
    requirement: 'Review 50 pull requests on GitHub',
    source: 'github',
  },
  {
    id: 'ach_8',
    title: 'Social Influencer',
    description: 'Gained 5,000+ followers on X',
    icon: 'megaphone',
    status: 'locked',
    progress: 0,
    maxProgress: 5000,
    requirement: 'Connect X and gain 5,000+ followers',
    source: 'twitter',
  },
  {
    id: 'ach_9',
    title: 'Thought Leader',
    description: 'Published 10+ articles or posts with high engagement',
    icon: 'pen-tool',
    status: 'locked',
    progress: 0,
    maxProgress: 10,
    requirement: 'Publish 10 articles with 100+ reactions each',
    source: 'linkedin',
  },
  {
    id: 'ach_10',
    title: 'Full Stack Verified',
    description: 'Complete profile with all integrations verified',
    icon: 'shield-check',
    status: 'locked',
    progress: 1,
    maxProgress: 3,
    requirement: 'Verify all platform integrations',
    source: 'multi',
  },
]

export const mockStats: AggregatedStats = {
  totalRepos: 156,
  totalFollowers: 8267,
  totalConnections: 5420,
  yearsExperience: 8,
  contributionsThisYear: 1234,
  skills: ['TypeScript', 'React', 'Node.js', 'Python', 'Go', 'PostgreSQL', 'AWS', 'Docker'],
}

export const mockReputation: ReputationData = {
  overallScore: 78,
  profileCompletion: 67,
  lastUpdated: '2026-04-08T08:00:00Z',
  factors: [
    {
      name: 'Open Source Contribution',
      score: 85,
      maxScore: 100,
      description: 'Based on repositories, stars, and contribution activity',
    },
    {
      name: 'Professional Network',
      score: 72,
      maxScore: 100,
      description: 'Based on LinkedIn connections and endorsements',
    },
    {
      name: 'Platform Verification',
      score: 65,
      maxScore: 100,
      description: 'Based on verified integrations and identity proofs',
    },
    {
      name: 'Community Engagement',
      score: 80,
      maxScore: 100,
      description: 'Based on followers, interactions, and content',
    },
  ],
}

export const mockActivity: ActivityEvent[] = [
  {
    id: 'act_1',
    type: 'achievement',
    title: 'Achievement Claimed',
    description: 'You claimed the "Industry Veteran" achievement',
    timestamp: '2026-04-07T12:30:00Z',
    platform: 'linkedin',
  },
  {
    id: 'act_2',
    type: 'verification',
    title: 'Verification Complete',
    description: 'GitHub account successfully verified',
    timestamp: '2026-04-01T10:30:00Z',
    platform: 'github',
  },
  {
    id: 'act_3',
    type: 'score_update',
    title: 'Trust Score Updated',
    description: 'Your reputation score increased by 5 points',
    timestamp: '2026-03-28T08:00:00Z',
  },
  {
    id: 'act_4',
    type: 'connection',
    title: 'Platform Connected',
    description: 'LinkedIn account connected successfully',
    timestamp: '2026-03-20T14:00:00Z',
    platform: 'linkedin',
  },
  {
    id: 'act_5',
    type: 'achievement',
    title: 'Achievement Unlocked',
    description: 'You unlocked "Open Source Pioneer"',
    timestamp: '2026-03-20T12:00:00Z',
    platform: 'github',
  },
]
